#!/bin/bash
#
# Munney Ubuntu Server - Initial Setup Script
# This script sets up the Ubuntu server for Munney deployment
#
# Usage: bash deploy/ubuntu/setup-server.sh
#

set -e  # Stop on errors

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${GREEN}🚀 Munney Ubuntu Server Setup${NC}"
echo "========================================="
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then
    echo -e "${RED}❌ Please do not run this script as root!${NC}"
    echo "Run as your regular user (lars). The script will use sudo when needed."
    exit 1
fi

# Step 1: Create Docker proxy network
echo -e "${BLUE}📡 Step 1: Checking Docker proxy network...${NC}"
if docker network inspect proxy >/dev/null 2>&1; then
    echo -e "${GREEN}✅ Docker proxy network already exists${NC}"
else
    echo -e "${YELLOW}Creating Docker proxy network...${NC}"
    docker network create proxy
    echo -e "${GREEN}✅ Docker proxy network created${NC}"
fi
echo ""

# Step 2: Create directories
echo -e "${BLUE}📁 Step 2: Creating project directories...${NC}"
sudo mkdir -p /srv/munney-dev
sudo mkdir -p /srv/munney-prod
sudo mkdir -p /srv/munney-dev/backups
sudo mkdir -p /srv/munney-prod/backups

# Set ownership to current user
sudo chown -R $USER:$USER /srv/munney-dev
sudo chown -R $USER:$USER /srv/munney-prod
echo -e "${GREEN}✅ Directories created${NC}"
echo ""

# Step 3: Setup GitHub SSH keys
echo -e "${BLUE}🔑 Step 3: Setting up GitHub SSH keys...${NC}"
if [ -f ~/.ssh/id_ed25519 ]; then
    echo -e "${YELLOW}SSH key already exists at ~/.ssh/id_ed25519${NC}"
    read -p "Generate new key? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        ssh-keygen -t ed25519 -C "your-server-munney" -f ~/.ssh/id_ed25519_munney
        SSH_KEY_FILE=~/.ssh/id_ed25519_munney
    else
        SSH_KEY_FILE=~/.ssh/id_ed25519
    fi
else
    echo -e "${YELLOW}Generating new SSH key...${NC}"
    ssh-keygen -t ed25519 -C "your-server-munney" -f ~/.ssh/id_ed25519
    SSH_KEY_FILE=~/.ssh/id_ed25519
fi

# Start SSH agent and add key
eval "$(ssh-agent -s)"
ssh-add $SSH_KEY_FILE

echo ""
echo -e "${GREEN}✅ SSH key ready!${NC}"
echo ""
echo -e "${YELLOW}=========================================${NC}"
echo -e "${YELLOW}📋 IMPORTANT: Add this SSH key to GitHub${NC}"
echo -e "${YELLOW}=========================================${NC}"
echo ""
cat ${SSH_KEY_FILE}.pub
echo ""
echo -e "${BLUE}Steps:${NC}"
echo "1. Copy the SSH key above (including 'ssh-ed25519' at the start)"
echo "2. Go to: https://github.com/settings/keys"
echo "3. Click 'New SSH key'"
echo "4. Title: your-server-munney"
echo "5. Paste the key and save"
echo ""
read -p "Press ENTER after you've added the key to GitHub..."

# Test GitHub connection
echo ""
echo -e "${BLUE}Testing GitHub connection...${NC}"
if ssh -T git@github.com 2>&1 | grep -q "successfully authenticated"; then
    echo -e "${GREEN}✅ GitHub SSH connection successful!${NC}"
else
    echo -e "${RED}❌ GitHub SSH connection failed${NC}"
    echo "Please check if you added the key correctly to GitHub"
    exit 1
fi
echo ""

# Step 4: Clone repositories
echo -e "${BLUE}📥 Step 4: Cloning Munney repository...${NC}"

# Development
if [ -d "/srv/munney-dev/.git" ]; then
    echo -e "${YELLOW}Dev repository already exists, skipping clone${NC}"
else
    echo -e "${YELLOW}Cloning to /srv/munney-dev (develop branch)...${NC}"
    git clone -b develop git@github.com:LarsMun/mister-munney.git /srv/munney-dev
fi

# Production
if [ -d "/srv/munney-prod/.git" ]; then
    echo -e "${YELLOW}Prod repository already exists, skipping clone${NC}"
else
    echo -e "${YELLOW}Cloning to /srv/munney-prod (main branch)...${NC}"
    git clone -b main git@github.com:LarsMun/mister-munney.git /srv/munney-prod
fi

echo -e "${GREEN}✅ Repositories cloned${NC}"
echo ""

# Step 5: Setup environment files
echo -e "${BLUE}⚙️  Step 5: Setting up environment files...${NC}"

# Generate random passwords and secrets
DEV_ROOT_PW=$(openssl rand -base64 24)
DEV_USER_PW=$(openssl rand -base64 24)
DEV_SECRET=$(openssl rand -hex 32)

PROD_ROOT_PW=$(openssl rand -base64 24)
PROD_USER_PW=$(openssl rand -base64 24)
PROD_SECRET=$(openssl rand -hex 32)

# Create dev .env
cat > /srv/munney-dev/.env << EOF
# Munney Development Environment Variables
# Auto-generated by setup script

# MySQL Database Credentials
MYSQL_ROOT_PASSWORD_DEV=${DEV_ROOT_PW}
MYSQL_PASSWORD_DEV=${DEV_USER_PW}

# Symfony App Secret
APP_SECRET_DEV=${DEV_SECRET}
EOF

# Create prod .env
cat > /srv/munney-prod/.env << EOF
# Munney Production Environment Variables
# Auto-generated by setup script

# MySQL Database Credentials
MYSQL_ROOT_PASSWORD_PROD=${PROD_ROOT_PW}
MYSQL_PASSWORD_PROD=${PROD_USER_PW}

# Symfony App Secret
APP_SECRET_PROD=${PROD_SECRET}
EOF

# Create backend .env files
cat > /srv/munney-dev/backend/.env << EOF
APP_ENV=dev
APP_DEBUG=true
APP_SECRET=${DEV_SECRET}
DATABASE_URL="mysql://money:${DEV_USER_PW}@database-dev:3306/money_db_dev?serverVersion=8.0&charset=utf8mb4"
CORS_ALLOW_ORIGIN='^https?://(devmunney\.home\.munne\.me|localhost)(:[0-9]+)?$'
EOF

cat > /srv/munney-prod/backend/.env << EOF
APP_ENV=prod
APP_DEBUG=false
APP_SECRET=${PROD_SECRET}
DATABASE_URL="mysql://money:${PROD_USER_PW}@database-prod:3306/money_db_prod?serverVersion=8.0&charset=utf8mb4"
CORS_ALLOW_ORIGIN='^https://munney\.home\.munne\.me$'
EOF

echo -e "${GREEN}✅ Environment files created${NC}"
echo ""

# Step 6: Summary
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}✅ Server setup complete!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo ""
echo "1. Deploy Development:"
echo -e "   ${YELLOW}cd /srv/munney-dev && bash deploy/ubuntu/deploy-dev.sh${NC}"
echo ""
echo "2. Deploy Production:"
echo -e "   ${YELLOW}cd /srv/munney-prod && bash deploy/ubuntu/deploy-prod.sh${NC}"
echo ""
echo -e "${BLUE}Access URLs:${NC}"
echo "   Development: https://devmunney.home.example.com"
echo "   Production:  https://munney.home.example.com"
echo ""
echo -e "${BLUE}Database credentials saved in:${NC}"
echo "   /srv/munney-dev/.env"
echo "   /srv/munney-prod/.env"
echo ""